stages:
  - test
  - build

lint-test-job:
  stage: test
  image: python:3.10-slim
  script:
    - pip install flake8
    - flake8 .

build-job:
  image: docker:dind
  stage: build
  services:
    - docker:dind
  script:
    - echo "Starting build..."
    - docker info
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t registry.gitlab.com/e-com-shop/backend/eshop-gateway-ms .
    - docker push registry.gitlab.com/e-com-shop/backend/eshop-gateway-ms
