# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorization.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uthorization.proto\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"2\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2a\n\rAuthorization\x12(\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\"\x00\x12&\n\x08Register\x12\x10.RegisterRequest\x1a\x06.Empty\"\x00\x42*Z(wensiet.authorization.v1;authorizationv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authorization_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(wensiet.authorization.v1;authorizationv1'
  _globals['_LOGINREQUEST']._serialized_start=23
  _globals['_LOGINREQUEST']._serialized_end=70
  _globals['_LOGINRESPONSE']._serialized_start=72
  _globals['_LOGINRESPONSE']._serialized_end=102
  _globals['_REGISTERREQUEST']._serialized_start=104
  _globals['_REGISTERREQUEST']._serialized_end=154
  _globals['_EMPTY']._serialized_start=156
  _globals['_EMPTY']._serialized_end=163
  _globals['_AUTHORIZATION']._serialized_start=165
  _globals['_AUTHORIZATION']._serialized_end=262
# @@protoc_insertion_point(module_scope)
