version: '3'
services:
  gateway:
    build: .
    ports:
      - ":8000"
    networks:
      - eshop
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - eshop


networks:
  eshop:
    external: true