# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\x12\x07product\"Z\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x10\n\x08quantity\x18\x05 \x01(\x05\"\x1f\n\x11GetProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x12GetProductResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"1\n\x12GetProductsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"H\n\x13GetProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.product.Product\x12\r\n\x05total\x18\x02 \x01(\x05\"[\n\x14\x43reateProductRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"#\n\x15\x43reateProductResponse\x12\n\n\x02id\x18\x01 \x01(\t\"T\n\x14UpdateProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x02\":\n\x15UpdateProductResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product\"\"\n\x14\x44\x65leteProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"#\n\x15\x44\x65leteProductResponse\x12\n\n\x02id\x18\x01 \x01(\t2\xf5\x02\n\x0bProductServ\x12:\n\nGetProduct\x12\x1a.product.GetProductRequest\x1a\x10.product.Product\x12H\n\x0bGetProducts\x12\x1b.product.GetProductsRequest\x1a\x1c.product.GetProductsResponse\x12N\n\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x1e.product.CreateProductResponse\x12@\n\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x10.product.Product\x12N\n\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponseB\x1eZ\x1cwensiet.product.v1;productv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034wensiet.product.v1;productv1'
  _globals['_PRODUCT']._serialized_start=27
  _globals['_PRODUCT']._serialized_end=117
  _globals['_GETPRODUCTREQUEST']._serialized_start=119
  _globals['_GETPRODUCTREQUEST']._serialized_end=150
  _globals['_GETPRODUCTRESPONSE']._serialized_start=152
  _globals['_GETPRODUCTRESPONSE']._serialized_end=207
  _globals['_GETPRODUCTSREQUEST']._serialized_start=209
  _globals['_GETPRODUCTSREQUEST']._serialized_end=258
  _globals['_GETPRODUCTSRESPONSE']._serialized_start=260
  _globals['_GETPRODUCTSRESPONSE']._serialized_end=332
  _globals['_CREATEPRODUCTREQUEST']._serialized_start=334
  _globals['_CREATEPRODUCTREQUEST']._serialized_end=425
  _globals['_CREATEPRODUCTRESPONSE']._serialized_start=427
  _globals['_CREATEPRODUCTRESPONSE']._serialized_end=462
  _globals['_UPDATEPRODUCTREQUEST']._serialized_start=464
  _globals['_UPDATEPRODUCTREQUEST']._serialized_end=548
  _globals['_UPDATEPRODUCTRESPONSE']._serialized_start=550
  _globals['_UPDATEPRODUCTRESPONSE']._serialized_end=608
  _globals['_DELETEPRODUCTREQUEST']._serialized_start=610
  _globals['_DELETEPRODUCTREQUEST']._serialized_end=644
  _globals['_DELETEPRODUCTRESPONSE']._serialized_start=646
  _globals['_DELETEPRODUCTRESPONSE']._serialized_end=681
  _globals['_PRODUCTSERV']._serialized_start=684
  _globals['_PRODUCTSERV']._serialized_end=1057
# @@protoc_insertion_point(module_scope)
