env: local
port: 8000
domain: http://localhost/media
path: "/api/v1"
sentry: https://667b4cfbf3b29df190748ccac1ee04d8@o4506655030378496.ingest.sentry.io/4506655032147968
products:
  host: eshop-products-service
  port: 9090
authorization:
  host: eshop-auth-service
  port: 9091
loki:
  host: 213.226.125.222
  port: 3100
redis:
  host: eshop-redis-service
  port: 6379
  db: 2
  password: pass
